"""Evaluate a completed run while protecting the fixed held-out test protocol."""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import shutil
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, Sequence

from fruit_ssod.data.class_mapping import DEFAULT_CLASS_REGISTRY
from fruit_ssod.detection.adapter import DetectorAdapterError, validate_class_mapping
from fruit_ssod.training.run_record import RunRecordError, read_run_record
from fruit_ssod.training.supervised import SupervisedTrainingError, _dataset_evidence, _serialize_metric_object, file_evidence


# FruitDet is deliberately a four-class external protocol.  It is not a
# second five-class test set: Pineapple is absent and must never be inserted
# into its reported aggregate by inference from the detector registry.
_FRUITDET_PROTOCOL = {
    "protocol_id": "fruitdet_external_mapped_v1",
    "mapping_source": "limited_external_set",
    "mapped_class_ids": [0, 1, 2, 3],
    "mapped_class_names": ["Apple", "Banana", "Orange", "Strawberry"],
}

_EVALUATOR_ARTIFACTS = {
    "precision_recall": ("PR_curve.png",),
    "confusion_matrix": ("confusion_matrix.png",),
}


@dataclass(frozen=True)
class EvaluationExecution:
    """Metrics plus evaluator-owned visual artifacts copied into run evidence."""

    metrics: Mapping[str, Any]
    raw_evaluator_outputs: Mapping[str, Mapping[str, Any]]


def _problem(problem: str, cause: str, remediation: str) -> SupervisedTrainingError:
    return SupervisedTrainingError(f"Problem: {problem}. Likely cause: {cause}. Remediation: {remediation}.")


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Evaluate a recorded fruit detector run.")
    parser.add_argument("--run-dir", type=Path, required=True, help="Directory containing run_record.json and weights/best.pt.")
    parser.add_argument("--split", choices=("validation", "test", "external_test"), required=True, help="Dataset protocol split to evaluate.")
    parser.add_argument("--data", type=Path, help="Optional dataset YAML; required for an external test dataset.")
    parser.add_argument("--fruitdet-manifest", type=Path, help="Sealed manifest.json emitted by import_auxiliary_data fruitdet; required with --split external_test.")
    parser.add_argument("--device", help="Override the recorded device.")
    parser.add_argument("--dry-run", action="store_true", help="Validate authorization and paths without loading a model.")
    return parser


def _snapshot_path(snapshot: Mapping[str, Any], key: str) -> Path:
    value = snapshot.get(key)
    if not isinstance(value, str) or not value:
        raise _problem("run record lacks required configuration", f"config_snapshot.{key} is missing", "use a complete run_record.json generated by train_supervised")
    return Path(value)


def _canonical_dataset_evidence(data: Path, *, protocol: str) -> tuple[Path, dict[str, Any], str]:
    """Resolve and validate an evaluation YAML under the five-class contract."""
    try:
        resolved = data.resolve(strict=True)
    except OSError as error:
        raise _problem("evaluation dataset YAML cannot be resolved", str(error), "restore the recorded YAML or pass a readable external-test YAML") from error
    if not resolved.is_file():
        raise _problem("evaluation dataset YAML is missing", f"{resolved} is not a file", "restore the required dataset YAML")
    try:
        effective, digest = _dataset_evidence(resolved)
    except SupervisedTrainingError as error:
        raise _problem(f"{protocol} dataset YAML violates the canonical class contract", str(error), "use Apple, Banana, Orange, Strawberry, Pineapple in IDs 0 through 4") from error
    return resolved, effective, digest


def _recorded_test_dataset(record: Any) -> tuple[Path, dict[str, Any], str]:
    """Use precisely the YAML and content digest frozen with a completed run."""
    snapshot = record.config_snapshot
    data, effective, digest = _canonical_dataset_evidence(_snapshot_path(snapshot, "dataset_yaml"), protocol="held-out test")
    expected_digest = snapshot.get("dataset_yaml_sha256")
    if not isinstance(expected_digest, str) or len(expected_digest) != 64:
        raise _problem("run record lacks held-out dataset digest", "config_snapshot.dataset_yaml_sha256 is missing or malformed", "use the untouched run_record.json emitted by train_supervised")
    if digest != expected_digest:
        raise _problem("held-out test dataset YAML changed after training", f"recorded SHA-256 is {expected_digest}, current SHA-256 is {digest}", "restore the exact recorded dataset YAML; do not evaluate an altered test protocol")
    return data, effective, digest


def _verify_best_checkpoint(run_dir: Path) -> dict[str, Any]:
    """Prove held-out evaluation uses the exact checkpoint from completion.

    ``checkpoint_evidence.json`` deliberately records a portable relative
    path plus byte count and SHA-256.  All three are checked before even a
    dry-run authorization succeeds, preventing a replaced, truncated, or
    differently located weight file from being presented as the completed
    model.
    """
    evidence_path = run_dir / "checkpoint_evidence.json"
    try:
        payload = json.loads(evidence_path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as error:
        raise _problem("checkpoint evidence cannot be read", str(error), "restore the checkpoint_evidence.json saved with the completed run") from error
    if not isinstance(payload, Mapping) or not isinstance(payload.get("best.pt"), Mapping):
        raise _problem("best checkpoint evidence is missing", "checkpoint_evidence.json has no best.pt object", "restore the original completion evidence before test evaluation")
    expected = payload["best.pt"]
    expected_relative = expected.get("relative_path")
    expected_bytes = expected.get("bytes")
    expected_sha256 = expected.get("sha256")
    if expected_relative != "weights/best.pt":
        raise _problem("best checkpoint relative path does not match", f"recorded {expected_relative!r}, expected 'weights/best.pt'", "restore evidence for the run's weights/best.pt checkpoint")
    if isinstance(expected_bytes, bool) or not isinstance(expected_bytes, int) or expected_bytes <= 0:
        raise _problem("best checkpoint byte evidence is malformed", f"recorded {expected_bytes!r}", "restore a positive byte count in checkpoint_evidence.json")
    if not isinstance(expected_sha256, str) or len(expected_sha256) != 64 or any(character not in "0123456789abcdef" for character in expected_sha256.lower()):
        raise _problem("best checkpoint SHA-256 evidence is malformed", f"recorded {expected_sha256!r}", "restore the 64-character checkpoint SHA-256 from completion")
    weights = run_dir / "weights" / "best.pt"
    actual = file_evidence(weights, description="best checkpoint for held-out evaluation")
    if actual["bytes"] != expected_bytes or actual["sha256"] != expected_sha256.lower():
        raise _problem("best checkpoint differs from completion evidence", f"expected {expected_bytes} bytes / {expected_sha256.lower()}, got {actual['bytes']} bytes / {actual['sha256']}", "restore the exact nonempty weights/best.pt saved when training completed")
    return actual


def _metrics_sha256(metrics: Mapping[str, Any]) -> str:
    """Return a deterministic digest of the canonical metric payload."""
    encoded = json.dumps(metrics, ensure_ascii=False, sort_keys=True, separators=(",", ":"), allow_nan=False)
    return hashlib.sha256(encoded.encode("utf-8")).hexdigest()


def _fruitdet_manifest_evidence(path: Path) -> dict[str, Any]:
    """Verify that external evaluation is the reviewed FruitDet protocol.

    A five-class YAML alone is intentionally insufficient: any unrelated
    dataset could be made to look canonical that way.  The separately sealed
    importer manifest carries the source, mapping and human-label provenance
    for the four FruitDet classes.
    """
    evidence = file_evidence(path, description="sealed FruitDet importer manifest")
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as error:
        raise _problem("sealed FruitDet importer manifest cannot be read", str(error), "pass the untouched manifest.json emitted by import_auxiliary_data fruitdet") from error
    if not isinstance(payload, Mapping):
        raise _problem("sealed FruitDet importer manifest is malformed", "manifest top level is not an object", "pass the untouched FruitDet importer manifest")
    source = payload.get("source")
    expected_ids = list(_FRUITDET_PROTOCOL["mapped_class_ids"])
    expected_names = list(_FRUITDET_PROTOCOL["mapped_class_names"])
    if (
        not isinstance(source, Mapping)
        or source.get("name") != "fruitdet"
        or payload.get("category_mapping_source") != "limited_external_set"
        or payload.get("split") != "external_test"
        or payload.get("label_status") != "labeled"
        or payload.get("mapped_class_ids") != expected_ids
        or payload.get("mapped_class_names") != expected_names
    ):
        raise _problem(
            "external test is not a sealed FruitDet import",
            "manifest must identify source=fruitdet, limited_external_set, external_test/labeled, and the reviewed four mapped categories",
            "regenerate the manifest with import_auxiliary_data fruitdet and pass that untouched manifest",
        )
    records = payload.get("records")
    if not isinstance(records, list) or not records:
        raise _problem("sealed FruitDet importer manifest has no accepted records", "there is no imported external-test evidence to evaluate", "provide a FruitDet manifest with at least one accepted mapped annotation")
    observed_class_ids: set[int] = set()
    for row in records:
        if not isinstance(row, Mapping) or row.get("source_dataset") != "fruitdet" or row.get("source") != "limited_external_set" or row.get("split") != "external_test" or row.get("label_status") != "labeled":
            raise _problem("sealed FruitDet importer manifest has an invalid record", "an accepted record lacks FruitDet external-test provenance", "restore the untouched FruitDet importer manifest")
        class_id = row.get("class_id")
        if isinstance(class_id, bool) or not isinstance(class_id, int) or class_id not in expected_ids:
            raise _problem("sealed FruitDet importer manifest has an unsupported mapped category", f"record class_id is {class_id!r}", "use only Apple, Banana, Orange, and Strawberry mapped by limited_external_set")
        observed_class_ids.add(class_id)
    # The source declaration remains a reviewed four-class mapping, but a
    # particular immutable source revision may not contain samples from every
    # declared class.  Record that fact explicitly and require metrics to use
    # exactly these observed classes; never invent zero AP for absent data.
    observed = sorted(observed_class_ids)
    return {
        "path": str(path.resolve()), "bytes": evidence["bytes"], "sha256": evidence["sha256"],
        "source": "fruitdet", "mapping_source": "limited_external_set",
        "mapped_class_ids": expected_ids, "mapped_class_names": expected_names,
        "observed_class_ids": observed,
        "observed_class_names": [DEFAULT_CLASS_REGISTRY.class_names[index] for index in observed],
    }


def _canonical_membership(paths: set[str]) -> str:
    return hashlib.sha256(json.dumps(sorted(paths), ensure_ascii=False, separators=(",", ":"), allow_nan=False).encode("utf-8")).hexdigest()


def fruitdet_dataset_binding(data: Path, effective_data: Mapping[str, Any], dataset_sha256: str, manifest_evidence: Mapping[str, Any]) -> dict[str, Any]:
    """Prove the evaluated FruitDet images exactly equal sealed manifest members."""
    manifest_path = Path(str(manifest_evidence["path"]))
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        records = manifest["records"]
        if not isinstance(records, list) or not records or any(not isinstance(row, Mapping) or not isinstance(row.get("file_path"), str) or not row.get("file_path") for row in records):
            raise ValueError("records is absent or empty")
        manifest_members = {str(Path(str(row["file_path"])).resolve(strict=True)) for row in records}
    except (OSError, UnicodeDecodeError, json.JSONDecodeError, KeyError, TypeError, ValueError) as error:
        raise _problem("FruitDet manifest cannot prove image membership", str(error), "regenerate the importer manifest with readable file_path values for every accepted record") from error
    reference = effective_data.get("test")
    try:
        if isinstance(reference, str):
            list_path = Path(reference)
            if list_path.suffix.lower() != ".txt" or not list_path.is_file():
                raise ValueError("test must be a readable .txt image list, not a directory")
            values = [line.strip() for line in list_path.read_text(encoding="utf-8").splitlines() if line.strip()]
            resolved_members = [str((Path(value) if Path(value).is_absolute() else list_path.parent / value).resolve(strict=True)) for value in values]
        elif isinstance(reference, list) and all(isinstance(value, str) for value in reference):
            resolved_members = [str(Path(value).resolve(strict=True)) for value in reference]
        else:
            raise ValueError("test is not a concrete image list")
    except (OSError, ValueError) as error:
        raise _problem("FruitDet YAML test membership cannot be resolved", str(error), "use a readable .txt list or explicit image paths matching the sealed importer manifest") from error
    evaluated_members = set(resolved_members)
    if len(resolved_members) != len(evaluated_members):
        raise _problem("FruitDet YAML test membership contains duplicate resolved image paths", "a duplicate line or aliased path would be hidden by set comparison", "generate one normalized image-list entry per imported FruitDet image")
    if not evaluated_members or evaluated_members != manifest_members:
        raise _problem("FruitDet YAML membership differs from sealed manifest", "the evaluated external image set has missing or unrelated members", "generate the external YAML test list directly from the FruitDet importer manifest")
    membership_sha256 = _canonical_membership(manifest_members)
    fingerprint = hashlib.sha256(json.dumps({"dataset_yaml_sha256": dataset_sha256, "fruitdet_manifest_sha256": manifest_evidence["sha256"], "membership_sha256": membership_sha256}, sort_keys=True, separators=(",", ":"), allow_nan=False).encode("utf-8")).hexdigest()
    return {"membership_sha256": membership_sha256, "member_count": len(manifest_members), "dataset_fingerprint": fingerprint}


def _capture_evaluator_artifacts(source: Path, destination: Path, *, split: str) -> dict[str, dict[str, Any]]:
    """Copy the framework's raw plots and seal the copied bytes.

    Only framework-produced files from the dedicated temporary output root are
    copied.  Later reporting uses the copied evidence, never an untracked
    framework cache path.
    """
    if destination.exists() or destination.is_symlink():
        raise _problem("raw evaluator output already exists", str(destination), "preserve the original evaluation evidence or evaluate in a new run directory")
    destination.mkdir(parents=True)
    captured: dict[str, dict[str, Any]] = {}
    for public_name, candidate_names in _EVALUATOR_ARTIFACTS.items():
        matches = [candidate for name in candidate_names for candidate in source.rglob(name) if candidate.is_file() and not candidate.is_symlink()]
        if len(matches) > 1:
            raise _problem("raw evaluator artifact is ambiguous", f"Ultralytics produced {len(matches)} candidates for {public_name} beneath {source}", "use a fresh empty evaluator output directory")
        found = matches[0] if matches else None
        if found is None:
            continue
        target = destination / found.name
        shutil.copyfile(found, target)
        evidence = file_evidence(target, description=f"Ultralytics {public_name} evaluator artifact")
        captured[public_name] = {
            "path": str(target.resolve()),
            "relative_path": target.relative_to(destination.parents[2]).as_posix(),
            "bytes": evidence["bytes"],
            "sha256": evidence["sha256"],
            "source_filename": found.name,
            "split": split,
        }
    return captured


def _external_metric_mapping(metrics: Any, *, expected_class_ids: Sequence[int]) -> dict[str, Any]:
    """Serialize a partial-coverage external test without fabricating classes.

    Ultralytics emits one AP row per class that has ground-truth instances in
    the evaluated split and exposes its canonical IDs through
    ``box.ap_class_index``.  Unlike primary evaluation, external FruitDet
    evidence must preserve that narrower observed scope instead of forcing the
    five-class ``DetectionMetrics`` contract.
    """
    expected = list(expected_class_ids)
    if not expected or any(isinstance(value, bool) or not isinstance(value, int) or value not in _FRUITDET_PROTOCOL["mapped_class_ids"] for value in expected) or expected != sorted(set(expected)):
        raise _problem("external observed classes are invalid", repr(expected), "derive sorted unique FruitDet class IDs from the sealed manifest")
    try:
        box = getattr(metrics, "box")
        all_ap = getattr(box, "all_ap")
        rows = all_ap.tolist() if hasattr(all_ap, "tolist") else list(all_ap)
        class_indices = getattr(box, "ap_class_index")
        observed = class_indices.tolist() if hasattr(class_indices, "tolist") else list(class_indices)
        if any(isinstance(value, bool) or not isinstance(value, int) for value in observed):
            raise ValueError("ap_class_index contains a non-integer canonical class ID")
        if observed != expected:
            raise ValueError(f"Ultralytics reported class IDs {observed!r}, expected exactly observed source IDs {expected!r}")
        if len(rows) != len(observed) or any(not isinstance(row, Sequence) or isinstance(row, (str, bytes)) or not row for row in rows):
            raise ValueError("all_ap does not have one nonempty AP row per reported class")
        values = [float(row[0]) for row in rows]
        overall = {
            "map50": float(getattr(box, "map50")), "map50_95": float(getattr(box, "map")),
            "precision": float(getattr(box, "mp")), "recall": float(getattr(box, "mr")),
        }
        overall["f1"] = (2 * overall["precision"] * overall["recall"] / (overall["precision"] + overall["recall"])) if overall["precision"] + overall["recall"] else 0.0
        if any(not math.isfinite(value) or not 0 <= value <= 1 for value in [*overall.values(), *values]):
            raise ValueError("one or more normalized detection metrics is non-finite or outside [0, 1]")
        return {**overall, "reported_class_ids": observed, "per_class_ap50": {str(class_id): value for class_id, value in zip(observed, values, strict=True)}}
    except (AttributeError, TypeError, ValueError) as error:
        raise _problem("Ultralytics external validation output is incompatible", str(error), "use a supported detection version exposing all_ap and ap_class_index for the sealed external classes") from error


def _validated_external_metric_mapping(metrics: Mapping[str, Any], *, expected_class_ids: Sequence[int]) -> dict[str, Any]:
    """Validate persisted/executor external metrics against actual source scope."""
    expected = list(expected_class_ids)
    try:
        if set(metrics) != {"map50", "map50_95", "precision", "recall", "f1", "reported_class_ids", "per_class_ap50"}:
            raise ValueError("external metrics keys are incomplete or unexpected")
        reported = metrics["reported_class_ids"]
        per_class = metrics["per_class_ap50"]
        if reported != expected:
            raise ValueError(f"reported_class_ids must exactly equal observed source IDs {expected!r}")
        if not isinstance(per_class, Mapping) or set(per_class) != {str(value) for value in expected}:
            raise ValueError("per_class_ap50 keys must exactly equal reported external class IDs")
        normalized: dict[str, Any] = {"reported_class_ids": list(reported), "per_class_ap50": {str(value): float(per_class[str(value)]) for value in expected}}
        for name in ("map50", "map50_95", "precision", "recall", "f1"):
            value = metrics[name]
            if isinstance(value, bool) or not isinstance(value, (int, float)) or not math.isfinite(float(value)) or not 0 <= float(value) <= 1:
                raise ValueError(f"{name} is not a finite normalized metric")
            normalized[name] = float(value)
        if any(not math.isfinite(value) or not 0 <= value <= 1 for value in normalized["per_class_ap50"].values()):
            raise ValueError("per_class_ap50 contains a non-finite or unnormalized value")
        return {name: normalized[name] for name in ("map50", "map50_95", "precision", "recall", "f1", "reported_class_ids", "per_class_ap50")}
    except (KeyError, TypeError, ValueError) as error:
        raise _problem("external evaluation metrics do not match actual FruitDet coverage", str(error), "report exactly the sealed manifest's observed class IDs without padding absent categories") from error


def _evaluate(run_dir: Path, record: Any, *, split: str, data: Path, device: str | None, external_class_ids: Sequence[int] | None = None) -> EvaluationExecution:
    weights = run_dir / "weights" / "best.pt"
    if not weights.is_file():
        raise _problem("best checkpoint is missing", f"{weights} does not exist", "complete training successfully or select its preserved run directory")
    try:
        from ultralytics import YOLO
    except ModuleNotFoundError as error:
        raise _problem("Ultralytics is not installed", "the active Conda environment lacks the evaluation dependency", "install the locked project dependencies") from error
    try:
        model = YOLO(str(weights))
        validate_class_mapping(getattr(model, "names", None), DEFAULT_CLASS_REGISTRY)
        snapshot = record.config_snapshot
        evaluations = run_dir / "evaluations"
        evaluations.mkdir(parents=True, exist_ok=True)
        with tempfile.TemporaryDirectory(prefix=f".{split}.ultralytics.", dir=evaluations) as temporary:
            temporary_root = Path(temporary)
            metrics = model.val(
                data=str(data), split="test" if split in {"test", "external_test"} else "val",
                imgsz=snapshot["image_size"], device=device or snapshot["device"], verbose=False,
                plots=True, project=str(temporary_root), name="raw", exist_ok=False,
            )
            source = temporary_root / "raw"
            # Ultralytics normally respects project/name.  Keeping the
            # fallback local to our temporary root supports compatible
            # versions that return a different direct save directory.
            candidate = getattr(metrics, "save_dir", None)
            if not source.is_dir() and isinstance(candidate, (str, Path)):
                candidate_path = Path(candidate)
                try:
                    candidate_path.resolve(strict=True).relative_to(temporary_root.resolve(strict=True))
                except (OSError, ValueError):
                    pass
                else:
                    source = candidate_path
            raw = _capture_evaluator_artifacts(source if source.is_dir() else temporary_root, evaluations / "raw" / split, split=split)
            serialized = _external_metric_mapping(metrics, expected_class_ids=external_class_ids or ()) if split == "external_test" else _serialize_metric_object(metrics).mapping()
            return EvaluationExecution(serialized, raw)
    except DetectorAdapterError as error:
        raise _problem("checkpoint class mapping is incompatible", str(error), "evaluate only a five-class canonical fruit checkpoint") from error
    except SupervisedTrainingError:
        raise
    except Exception as error:
        raise _problem("model evaluation failed", str(error), "check data YAML, split names, weights, and the requested device") from error


def main(argv: Sequence[str] | None = None) -> int:
    parser = _parser()
    args = parser.parse_args(argv)
    try:
        run_dir = args.run_dir.resolve(strict=True)
        if not run_dir.is_dir():
            raise _problem("run directory is not a directory", f"{run_dir} is not a run artifact directory", "pass the directory containing run_record.json")
        record = read_run_record(run_dir / "run_record.json")
        if record.status != "complete":
            raise _problem("evaluation is not authorized", f"run {record.run_id} is {record.status}, not complete", "finish the exact recorded training run before producing evaluation evidence")
        checkpoint = _verify_best_checkpoint(run_dir)
        if args.split == "test" and args.data is not None:
            raise _problem("held-out test dataset override is forbidden", "--data would replace the exact YAML frozen with the training run", "remove --data; test evaluation must use the recorded dataset YAML and SHA-256")
        if args.split == "external_test" and args.data is None:
            raise _problem("external test dataset is unspecified", "the primary dataset YAML must not be silently reused for FruitDet", "pass --data with the separately prepared FruitDet dataset YAML")
        if args.split == "external_test" and args.fruitdet_manifest is None:
            raise _problem("sealed FruitDet importer manifest is required", "an arbitrary canonical external YAML is not FruitDet evidence", "pass --fruitdet-manifest with the untouched import_auxiliary_data fruitdet manifest.json")
        if args.split != "external_test" and args.fruitdet_manifest is not None:
            raise _problem("FruitDet importer manifest is only valid for external_test", "primary validation/test must not inherit external provenance", "remove --fruitdet-manifest unless --split external_test")
        if args.split == "test":
            data, effective_data, data_digest = _recorded_test_dataset(record)
        elif args.split == "external_test":
            data, effective_data, data_digest = _canonical_dataset_evidence(args.data, protocol="external test")
            fruitdet_manifest = _fruitdet_manifest_evidence(args.fruitdet_manifest)
            fruitdet_binding = fruitdet_dataset_binding(data, effective_data, data_digest, fruitdet_manifest)
        else:
            selected = args.data if args.data is not None else _snapshot_path(record.config_snapshot, "dataset_yaml")
            data, effective_data, data_digest = _canonical_dataset_evidence(selected, protocol="validation")
        if args.dry_run:
            print(json.dumps({"run_id": record.run_id, "split": args.split, "status": record.status, "authorized": True}, sort_keys=True))
            return 0
        execution = _evaluate(run_dir, record, split=args.split, data=data, device=args.device, external_class_ids=fruitdet_manifest["observed_class_ids"] if args.split == "external_test" else None)
        # Test fixtures can replace the backend with a bare mapping.  Production
        # evaluation always uses EvaluationExecution and seals raw artifacts.
        if isinstance(execution, EvaluationExecution):
            metrics = dict(execution.metrics)
            raw_outputs = dict(execution.raw_evaluator_outputs)
        elif isinstance(execution, Mapping):
            metrics = dict(execution)
            raw_outputs = {}
        else:  # pragma: no cover - protects future backend adapters.
            raise _problem("evaluation backend returned an unsupported result", type(execution).__name__, "return metrics or EvaluationExecution from the detector evaluator")
        if args.split == "external_test":
            metrics = _validated_external_metric_mapping(metrics, expected_class_ids=fruitdet_manifest["observed_class_ids"])
        # The result is an evidence envelope, rather than a bare metrics JSON:
        # Task 12 aggregation verifies every binding before accepting a score.
        protocol: dict[str, Any] = {
            "schema": "fruit_ssod_evaluation_evidence_v1",
            "run_id": record.run_id,
            "checkpoint_sha256": checkpoint["sha256"],
            "dataset_yaml_sha256": data_digest,
            "split": args.split,
            "metrics_sha256": _metrics_sha256(metrics),
            "canonical_classes": list(DEFAULT_CLASS_REGISTRY.class_names),
            "raw_evaluator_outputs": raw_outputs,
        }
        if args.split == "external_test":
            # Seal the protocol beside the dataset digest so later aggregation
            # can prove it is reporting only FruitDet's reviewed mapped set.
            protocol.update({"dataset_yaml": str(data), "dataset_effective": effective_data, "external_protocol": _FRUITDET_PROTOCOL, "mapped_class_ids": _FRUITDET_PROTOCOL["mapped_class_ids"], "mapped_class_names": _FRUITDET_PROTOCOL["mapped_class_names"], "observed_class_ids": fruitdet_manifest["observed_class_ids"], "observed_class_names": fruitdet_manifest["observed_class_names"], "mapping_source": _FRUITDET_PROTOCOL["mapping_source"], "fruitdet_manifest": {**fruitdet_manifest, "membership_sha256": fruitdet_binding["membership_sha256"], "member_count": fruitdet_binding["member_count"]}, "fruitdet_dataset_fingerprint": fruitdet_binding["dataset_fingerprint"]})
        result: dict[str, Any] = {"schema_version": "1.0", "metrics": dict(metrics), "protocol": protocol}
        output = run_dir / "evaluations" / f"{args.split}.json"
        if output.exists():
            raise _problem("evaluation result already exists", f"{output} would be overwritten", "preserve the original result or use a new run for a new protocol")
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(json.dumps(result, sort_keys=True, indent=2) + "\n", encoding="utf-8")
    except (RunRecordError, SupervisedTrainingError, OSError, ValueError) as error:
        parser.error(str(error))
        return 2  # pragma: no cover
    print(json.dumps({"run_id": record.run_id, "split": args.split, "output": str(output), "result": result}, sort_keys=True))
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
