"""Data-only contracts reserved for a later open-world detector extension.

These types are intentionally not wired into the detector, training pipeline,
metrics, or GUI.  Version 1 accepts and displays only the five canonical fruit
classes.  A future implementation must explicitly review the evidence carried
by these proposals before changing the immutable production class registry.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from types import MappingProxyType
from pathlib import Path
from typing import Mapping, Protocol, Sequence, runtime_checkable

from fruit_ssod.detection.types import DetectionRecord


class KnownDetectionContractError(ValueError):
    """Raised when a known-class result breaches the first-version boundary."""


def _problem(problem: str, cause: str, remediation: str) -> str:
    return f"Problem: {problem}. Likely cause: {cause}. Remediation: {remediation}."


def _nonempty_text(value: object, field_name: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(
            _problem(
                f"{field_name} must be nonempty text",
                "the future-extension proposal is missing traceable metadata",
                f"provide a nonempty {field_name} without changing the current detector registry",
            )
        )
    return value.strip()


def _score(value: object, field_name: str) -> float:
    if isinstance(value, bool) or not isinstance(value, (int, float)) or not math.isfinite(value):
        raise ValueError(
            _problem(
                f"{field_name} must be a finite number",
                "the proposal score is malformed",
                f"provide a finite {field_name} in the inclusive range [0, 1]",
            )
        )
    result = float(value)
    if not 0.0 <= result <= 1.0:
        raise ValueError(
            _problem(
                f"{field_name} must be between 0 and 1",
                "the proposal score is outside probability bounds",
                f"provide a normalized {field_name} in the inclusive range [0, 1]",
            )
        )
    return result


def _xyxy(value: object) -> tuple[float, float, float, float]:
    if not isinstance(value, Sequence) or isinstance(value, (str, bytes)) or len(value) != 4:
        raise ValueError(
            _problem(
                "xyxy must contain four coordinates",
                "the proposal does not provide an XYXY box",
                "provide (x1, y1, x2, y2) with positive area",
            )
        )
    try:
        coordinates = tuple(float(item) for item in value)
    except (TypeError, ValueError) as error:
        raise ValueError(
            _problem(
                "xyxy coordinates must be numeric",
                "the proposal box contains non-numeric data",
                "provide finite numeric coordinates",
            )
        ) from error
    if not all(math.isfinite(item) for item in coordinates):
        raise ValueError(
            _problem(
                "xyxy coordinates must be finite",
                "the proposal box contains NaN or infinity",
                "provide finite numeric coordinates",
            )
        )
    x1, y1, x2, y2 = coordinates
    if not x1 < x2 or not y1 < y2:
        raise ValueError(
            _problem(
                "xyxy must have positive area",
                "the proposal box has zero or negative width or height",
                "provide a box with x1 < x2 and y1 < y2",
            )
        )
    return coordinates  # type: ignore[return-value]


@dataclass(frozen=True)
class UnknownProposal:
    """A reviewable *candidate* unknown region, not a deployed detection result.

    ``novelty_score`` may eventually be generated by an unknown-region method,
    but this project supplies no such method.  The absence of ``class_id`` and
    ``class_name`` is intentional: a candidate cannot enter the five-class
    detector taxonomy until it passes an explicit future registry review.
    """

    proposal_id: str
    image_id: str
    xyxy: tuple[float, float, float, float]
    novelty_score: float
    source_model: str
    evidence: Mapping[str, str]

    def __post_init__(self) -> None:
        object.__setattr__(self, "proposal_id", _nonempty_text(self.proposal_id, "proposal_id"))
        object.__setattr__(self, "image_id", _nonempty_text(self.image_id, "image_id"))
        object.__setattr__(self, "xyxy", _xyxy(self.xyxy))
        object.__setattr__(self, "novelty_score", _score(self.novelty_score, "novelty_score"))
        object.__setattr__(self, "source_model", _nonempty_text(self.source_model, "source_model"))
        if not isinstance(self.evidence, Mapping) or not self.evidence:
            raise ValueError(
                _problem(
                    "evidence must be a nonempty mapping",
                    "the future proposal is not auditable",
                    "record source run, image artifact, and review evidence before proposing a class update",
                )
            )
        normalized = {
            _nonempty_text(key, "evidence key"): _nonempty_text(item, "evidence value")
            for key, item in self.evidence.items()
        }
        object.__setattr__(self, "evidence", MappingProxyType(normalized))


@dataclass(frozen=True)
class UnknownProposalRequest:
    """Immutable input to a future unknown-region proposal provider.

    The request deliberately contains the image artifact, the fixed
    five-class detections already produced for it, and auditable run evidence.
    A future provider may *propose* review candidates from this context, but it
    must not replace known detections, allocate a class ID, or alter a class
    registry.  No provider implementation is included in version 1.
    """

    image_path: Path | str
    known_detections: tuple[DetectionRecord, ...]
    source_run_id: str
    evidence: Mapping[str, str]

    def __post_init__(self) -> None:
        if not isinstance(self.image_path, (Path, str)):
            raise ValueError(
                _problem(
                    "image_path must be a Path or nonempty path string",
                    "the future proposal request does not identify its source image",
                    "provide the image artifact path without changing the current detector output",
                )
            )
        path_text = str(self.image_path).strip()
        if not path_text:
            raise ValueError(
                _problem(
                    "image_path must be nonempty",
                    "the future proposal request does not identify its source image",
                    "provide the path of the image that produced the candidate",
                )
            )
        if not isinstance(self.known_detections, tuple):
            raise ValueError(
                _problem(
                    "known_detections must be a tuple",
                    "the future proposal request carries mutable detector output",
                    "supply an immutable tuple of validated known detections",
                )
            )
        object.__setattr__(self, "image_path", Path(path_text))
        object.__setattr__(self, "known_detections", assert_known_detection_results(self.known_detections))
        object.__setattr__(self, "source_run_id", _nonempty_text(self.source_run_id, "source_run_id"))
        if not isinstance(self.evidence, Mapping) or not self.evidence:
            raise ValueError(
                _problem(
                    "evidence must be a nonempty mapping",
                    "the future proposal request has no auditable provenance",
                    "record immutable source-run and image evidence before proposing unknown regions",
                )
            )
        normalized = {
            _nonempty_text(key, "evidence key"): _nonempty_text(item, "evidence value")
            for key, item in self.evidence.items()
        }
        object.__setattr__(self, "evidence", MappingProxyType(normalized))


@dataclass(frozen=True)
class ClassRegistryUpdateProposal:
    """A future, review-only request to extend the fixed class registry.

    This object never allocates a class ID and has no method that mutates
    :class:`~fruit_ssod.data.class_mapping.ClassRegistry`.  New canonical IDs,
    dataset protocol changes, and model retraining remain a separate approved
    future work item.
    """

    base_registry_version: str
    requested_class_name: str
    supporting_proposal_ids: tuple[str, ...]
    rationale: str

    def __post_init__(self) -> None:
        object.__setattr__(
            self, "base_registry_version", _nonempty_text(self.base_registry_version, "base_registry_version")
        )
        object.__setattr__(
            self, "requested_class_name", _nonempty_text(self.requested_class_name, "requested_class_name")
        )
        object.__setattr__(self, "rationale", _nonempty_text(self.rationale, "rationale"))
        if not isinstance(self.supporting_proposal_ids, tuple) or not self.supporting_proposal_ids:
            raise ValueError(
                _problem(
                    "supporting_proposal_ids must be a nonempty tuple",
                    "a registry update has no immutable evidence references",
                    "supply one or more reviewed UnknownProposal IDs",
                )
            )
        proposal_ids = tuple(_nonempty_text(item, "supporting proposal ID") for item in self.supporting_proposal_ids)
        if len(set(proposal_ids)) != len(proposal_ids):
            raise ValueError(
                _problem(
                    "supporting_proposal_ids must be unique",
                    "the same evidence proposal was supplied more than once",
                    "reference each reviewed proposal ID only once",
                )
            )
        object.__setattr__(self, "supporting_proposal_ids", proposal_ids)


@runtime_checkable
class UnknownProposalProvider(Protocol):
    """Future extension point for producing review-only unknown candidates."""

    def propose_unknowns(self, request: UnknownProposalRequest) -> tuple[UnknownProposal, ...]:
        """Return candidates for offline review; do not alter known detections."""


@runtime_checkable
class ClassRegistryUpdateProposer(Protocol):
    """Future extension point for creating a review-only registry-change request."""

    def propose_registry_update(
        self, *, proposals: tuple[UnknownProposal, ...], base_registry_version: str
    ) -> ClassRegistryUpdateProposal:
        """Create an un-applied request; it must not mutate the current registry."""


def assert_known_detection_results(results: Sequence[DetectionRecord]) -> tuple[DetectionRecord, ...]:
    """Enforce that version-1 detector consumers receive known fruit results only.

    The current :class:`DetectionRecord` constructor already rejects unknown
    records.  Keeping this boundary guard documents the rule for future
    adapters and prevents a later incompatible record-like object from quietly
    reaching GUI/export paths.
    """
    if isinstance(results, (str, bytes)) or not isinstance(results, Sequence):
        raise KnownDetectionContractError(
            _problem(
                "known detector results must be a sequence of DetectionRecord values",
                "an adapter bypassed the detector output contract",
                "return a tuple of validated DetectionRecord objects with is_unknown=False",
            )
        )
    validated = tuple(results)
    for index, result in enumerate(validated):
        if not isinstance(result, DetectionRecord):
            raise KnownDetectionContractError(
                _problem(
                    f"known detector result at index {index} is not a DetectionRecord",
                    "an adapter returned an unsupported record type",
                    "return validated DetectionRecord objects only",
                )
            )
        if result.is_unknown:
            raise KnownDetectionContractError(
                _problem(
                    f"known detector result at index {index} is marked unknown",
                    "open-world output was sent to the first-version consumer path",
                    "keep is_unknown=False until the separately reviewed open-world extension is delivered",
                )
            )
    return validated
